package co.tdevs.duplika.native

import android.content.Context
import org.json.JSONObject
import java.io.File
import java.security.MessageDigest

/**
 * The device identifiers one space presents as its own.
 *
 * Every value is generated by Duplika, not read from the device — deliberately, and for
 * two separate reasons.
 *
 * **The host cannot read most of them.** On API 29+ `getImei()` and `Build.getSerial()`
 * need `READ_PRIVILEGED_PHONE_STATE`, which is system-only; since API 23 the Wi-Fi and
 * Bluetooth MAC both come back as `02:00:00:00:00:00`. Only `ANDROID_ID` is readable, and
 * it is per-signing-key, so every clone shares Duplika's single value. A screen that
 * claimed to show "this device's identifiers" would be showing four blanks.
 *
 * **A space's identity should not be the device's anyway.** The point of a per-space
 * identifier set is that it is the space's.
 *
 * The stored file is the source of truth, not a derivation: a space's first set comes
 * from a hash of its profile id, but the user can hand-type any of the five afterwards,
 * and a value someone typed cannot be recomputed from anything. Regenerating uses a
 * random nonce rather than a counter, so a new set is genuinely new and the previous one
 * is gone for good — there is no going back to it.
 *
 * Written to `filesDir/space_identity/<virtualUserId>.json`, which every Duplika process
 * can read — including the Bcore stub processes, which run under the same UID. That is
 * the file a future engine override reads to answer a guest's own identifier queries;
 * see `engine-patches/`. **Until that override exists, guests still see the device's real
 * values and nothing here reaches them.**
 */
class SpaceIdentityStore(context: Context) {

    private val directory = File(context.applicationContext.filesDir, DIRECTORY)

    /** One space's identifier set. */
    data class Identity(
        val virtualUserId: Int,
        val revision: Int,
        val deviceId: String,
        val androidId: String,
        val serialNumber: String,
        val wifiMac: String,
        val bluetoothMac: String,
    ) {
        fun toMap(): Map<String, Any?> = mapOf(
            "virtualUserId" to virtualUserId,
            "revision" to revision,
            "deviceId" to deviceId,
            "androidId" to androidId,
            "serialNumber" to serialNumber,
            "wifiMac" to wifiMac,
            "bluetoothMac" to bluetoothMac,
        )
    }

    /**
     * This space's identifiers, generating them on first read.
     *
     * Derived rather than randomly stored, so a lost or corrupt file rebuilds the same
     * set instead of silently handing the space a new identity.
     */
    @Synchronized
    fun identity(profileId: String, virtualUserId: Int): Identity {
        stored(virtualUserId)?.let { return it }

        // No file yet: this space has never been looked at. Its first set is derived from
        // the profile id so two spaces never collide and the same space always starts
        // from the same place. Everything after that is stored, not derived.
        val identity = derive(profileId, virtualUserId, nonce = "")
        persist(profileId, virtualUserId, identity)
        return identity
    }

    /**
     * Replaces this space's identifiers with values the user typed.
     *
     * Validated here as well as in the UI: this is the only writer of the file a guest
     * process will read, and a malformed identifier is worse than a real one — an IMEI
     * with the wrong number of digits is detectably fake, where the device's own is
     * merely shared.
     */
    @Synchronized
    fun update(
        profileId: String,
        virtualUserId: Int,
        values: Map<String, String>,
    ): Result<Identity> {
        val current = identity(profileId, virtualUserId)
        val next = current.copy(
            revision = current.revision + 1,
            deviceId = values["deviceId"] ?: current.deviceId,
            androidId = values["androidId"] ?: current.androidId,
            serialNumber = values["serialNumber"] ?: current.serialNumber,
            wifiMac = values["wifiMac"] ?: current.wifiMac,
            bluetoothMac = values["bluetoothMac"] ?: current.bluetoothMac,
        )

        validate(next)?.let { return Result.failure(IllegalArgumentException(it)) }

        persist(profileId, virtualUserId, next)
        return Result.success(next)
    }

    /** The first structural problem with [identity], or null when it is well-formed. */
    private fun validate(identity: Identity): String? = when {
        !identity.deviceId.matches(DEVICE_ID) ->
            "A device ID is 14 to 16 digits."
        !identity.androidId.matches(ANDROID_ID) ->
            "An Android ID is 16 hexadecimal characters."
        !identity.serialNumber.matches(SERIAL) ->
            "A serial number is 1 to 32 letters and digits."
        !identity.wifiMac.matches(MAC) ->
            "A Wi-Fi MAC looks like 02:1a:2b:3c:4d:5e."
        !identity.bluetoothMac.matches(MAC) ->
            "A Bluetooth MAC looks like 02:1a:2b:3c:4d:5e."
        else -> null
    }

    /**
     * Throws away this space's identifiers and gives it a new random set.
     *
     * Random, not the next value of a counter: the point is a set nobody can relate to
     * the previous one. The old values are overwritten and not kept anywhere, so this
     * cannot be undone — which is why the UI asks first.
     */
    @Synchronized
    fun regenerate(profileId: String, virtualUserId: Int): Identity {
        val previous = readRevision(virtualUserId)
        val nonce = ByteArray(16).also(random::nextBytes)
            .joinToString("") { "%02x".format(it) }
        val identity = derive(profileId, virtualUserId, nonce)
            .copy(revision = previous + 1)
        persist(profileId, virtualUserId, identity)
        return identity
    }

    /** Drops a deleted space's file so its identity is not resurrected by a reused id. */
    @Synchronized
    fun forget(virtualUserId: Int) {
        runCatching { fileFor(virtualUserId).delete() }
    }

    private fun fileFor(virtualUserId: Int) = File(directory, "$virtualUserId.json")

    /** This space's stored set, or null when there is no readable file. */
    private fun stored(virtualUserId: Int): Identity? = try {
        val file = fileFor(virtualUserId)
        if (!file.isFile) {
            null
        } else {
            val json = JSONObject(file.readText())
            Identity(
                virtualUserId = virtualUserId,
                revision = json.optInt("revision", 0),
                deviceId = json.getString("deviceId"),
                androidId = json.getString("androidId"),
                serialNumber = json.getString("serialNumber"),
                wifiMac = json.getString("wifiMac"),
                bluetoothMac = json.getString("bluetoothMac"),
            )
        }
    } catch (_: Throwable) {
        // A truncated or half-written file is not a crash: the caller falls back to a
        // fresh derived set, which is the same outcome as a space nobody has touched.
        null
    }

    private fun readRevision(virtualUserId: Int): Int = try {
        val file = fileFor(virtualUserId)
        if (!file.isFile) 0 else JSONObject(file.readText()).optInt("revision", 0)
    } catch (_: Throwable) {
        // An unreadable file means the default identity, not a crash: the values are
        // derived, so revision 0 rebuilds exactly what the space started with.
        0
    }

    /**
     * Writes [identity] to this space's file, unless the file already says exactly that.
     *
     * The whole set is written, not just the revision: this file is what an engine
     * override will read from inside a guest process, where the profile id needed to
     * re-derive the values is not available.
     */
    private fun persist(profileId: String, virtualUserId: Int, identity: Identity) {
        try {
            val json = JSONObject(identity.toMap()).put("profileId", profileId).toString()
            val file = fileFor(virtualUserId)
            if (file.isFile && file.readText() == json) {
                return
            }
            if (!directory.exists()) directory.mkdirs()
            file.writeText(json)
        } catch (error: Throwable) {
            Slog.w(Slog.PROFILE, "Could not store space identity: ${error.message}")
        }
    }

    /**
     * Builds a well-formed set from a hash of the profile id and [nonce].
     *
     * An empty nonce is a space's first identity, which is therefore the same every time
     * for the same profile id — two spaces never collide, and a space that loses its file
     * before anyone edits it comes back as itself.
     */
    private fun derive(profileId: String, virtualUserId: Int, nonce: String): Identity {
        val seed = digest("$profileId#$nonce")

        return Identity(
            virtualUserId = virtualUserId,
            revision = 0,
            deviceId = imei(seed),
            androidId = hex(seed, offset = 8, bytes = 8),
            serialNumber = alnum(seed, offset = 16, count = 12),
            wifiMac = mac(seed, offset = 20),
            bluetoothMac = mac(seed, offset = 26),
        )
    }

    private fun digest(input: String): ByteArray =
        MessageDigest.getInstance("SHA-256").digest(input.toByteArray())

    /** 15 digits with a valid Luhn check digit, the shape a real IMEI has. */
    private fun imei(seed: ByteArray): String {
        val body = digits(seed, offset = 0, count = 14)
        var sum = 0
        for ((index, character) in body.withIndex()) {
            var digit = character - '0'
            // Luhn doubles every second digit counting from the right; with a 14-digit
            // body that is the even indices from the left.
            if (index % 2 == 1) {
                digit *= 2
                if (digit > 9) digit -= 9
            }
            sum += digit
        }
        return body + ((10 - sum % 10) % 10)
    }

    private fun digits(seed: ByteArray, offset: Int, count: Int): String =
        buildString(count) {
            for (index in 0 until count) {
                append((seed[(offset + index) % seed.size].toInt() and 0xFF) % 10)
            }
        }

    /**
     * Uppercase letters and digits, which is the shape a device serial actually has.
     *
     * Ambiguous characters are left out of the alphabet: a serial is something people
     * read off a screen and type somewhere else, and O against 0 costs more than the
     * two characters of entropy it buys.
     */
    private fun alnum(seed: ByteArray, offset: Int, count: Int): String =
        buildString(count) {
            for (index in 0 until count) {
                val byte = seed[(offset + index) % seed.size].toInt() and 0xFF
                append(SERIAL_ALPHABET[byte % SERIAL_ALPHABET.length])
            }
        }

    private fun hex(seed: ByteArray, offset: Int, bytes: Int): String =
        buildString(bytes * 2) {
            for (index in 0 until bytes) {
                append("%02x".format(seed[(offset + index) % seed.size].toInt() and 0xFF))
            }
        }

    private fun mac(seed: ByteArray, offset: Int): String =
        (0 until 6).joinToString(":") { index ->
            var octet = seed[(offset + index) % seed.size].toInt() and 0xFF
            if (index == 0) {
                // Clear the multicast bit and set the locally-administered one, so the
                // address is well-formed and cannot be mistaken for a vendor's range.
                octet = (octet and 0xFE) or 0x02
            }
            "%02x".format(octet)
        }

    private val random = java.security.SecureRandom()

    private companion object {
        val DEVICE_ID = Regex("^[0-9]{14,16}$")
        val ANDROID_ID = Regex("^[0-9a-fA-F]{16}$")
        val SERIAL = Regex("^[0-9A-Za-z]{1,32}$")
        val MAC = Regex("^([0-9a-fA-F]{2}:){5}[0-9a-fA-F]{2}$")

        const val DIRECTORY = "space_identity"

        /** No I, O, 0, 1: they are indistinguishable in most of the fonts this lands in. */
        const val SERIAL_ALPHABET = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"
    }
}
