package co.tdevs.duplika.native

import android.content.Context
import org.json.JSONObject
import java.io.File
import java.security.MessageDigest

/**
 * The device identifiers one space presents as its own.
 *
 * Every value is generated by Duplika, not read from the device — deliberately, and for
 * two separate reasons.
 *
 * **The host cannot read most of them.** On API 29+ `getImei()` and `Build.getSerial()`
 * need `READ_PRIVILEGED_PHONE_STATE`, which is system-only; since API 23 the Wi-Fi and
 * Bluetooth MAC both come back as `02:00:00:00:00:00`. Only `ANDROID_ID` is readable, and
 * it is per-signing-key, so every clone shares Duplika's single value. A screen that
 * claimed to show "this device's identifiers" would be showing four blanks.
 *
 * **A space's identity should not be the device's anyway.** The point of a per-space
 * identifier set is that it is the space's, so it is derived from the profile id and a
 * revision number: stable across restarts, different per space, and regenerable.
 *
 * Written to `filesDir/space_identity/<virtualUserId>.json`, which every Duplika process
 * can read — including the Bcore stub processes, which run under the same UID. That is
 * the file a future engine override reads to answer a guest's own identifier queries;
 * see `engine-patches/`. **Until that override exists, guests still see the device's real
 * values and nothing here reaches them.**
 */
class SpaceIdentityStore(context: Context) {

    private val directory = File(context.applicationContext.filesDir, DIRECTORY)

    /** One space's identifier set. */
    data class Identity(
        val virtualUserId: Int,
        val revision: Int,
        val deviceId: String,
        val androidId: String,
        val serialNumber: String,
        val wifiMac: String,
        val bluetoothMac: String,
    ) {
        fun toMap(): Map<String, Any?> = mapOf(
            "virtualUserId" to virtualUserId,
            "revision" to revision,
            "deviceId" to deviceId,
            "androidId" to androidId,
            "serialNumber" to serialNumber,
            "wifiMac" to wifiMac,
            "bluetoothMac" to bluetoothMac,
        )
    }

    /**
     * This space's identifiers, generating them on first read.
     *
     * Derived rather than randomly stored, so a lost or corrupt file rebuilds the same
     * set instead of silently handing the space a new identity.
     */
    @Synchronized
    fun identity(profileId: String, virtualUserId: Int): Identity {
        val identity = derive(profileId, virtualUserId, readRevision(virtualUserId))
        // A read writes too, whenever the file does not already say exactly this: a
        // space nobody has modified has no file at all, and one written before a change
        // to how a value is shaped holds values this screen no longer shows. The file is
        // the only copy a guest process can read, so leaving it stale or absent would
        // point the engine override at the wrong identity.
        persist(profileId, virtualUserId, identity)
        return identity
    }

    /** Gives this space a new identity. Returns the new set. */
    @Synchronized
    fun regenerate(profileId: String, virtualUserId: Int): Identity {
        val next = readRevision(virtualUserId) + 1
        val identity = derive(profileId, virtualUserId, next)
        persist(profileId, virtualUserId, identity)
        return identity
    }

    /** Returns this space to the identity it was first given. */
    @Synchronized
    fun reset(profileId: String, virtualUserId: Int): Identity {
        val identity = derive(profileId, virtualUserId, 0)
        persist(profileId, virtualUserId, identity)
        return identity
    }

    /** Drops a deleted space's file so its identity is not resurrected by a reused id. */
    @Synchronized
    fun forget(virtualUserId: Int) {
        runCatching { fileFor(virtualUserId).delete() }
    }

    private fun fileFor(virtualUserId: Int) = File(directory, "$virtualUserId.json")

    private fun readRevision(virtualUserId: Int): Int = try {
        val file = fileFor(virtualUserId)
        if (!file.isFile) 0 else JSONObject(file.readText()).optInt("revision", 0)
    } catch (_: Throwable) {
        // An unreadable file means the default identity, not a crash: the values are
        // derived, so revision 0 rebuilds exactly what the space started with.
        0
    }

    /**
     * Writes [identity] to this space's file, unless the file already says exactly that.
     *
     * The whole set is written, not just the revision: this file is what an engine
     * override will read from inside a guest process, where the profile id needed to
     * re-derive the values is not available.
     */
    private fun persist(profileId: String, virtualUserId: Int, identity: Identity) {
        try {
            val json = JSONObject(identity.toMap()).put("profileId", profileId).toString()
            val file = fileFor(virtualUserId)
            if (file.isFile && file.readText() == json) {
                return
            }
            if (!directory.exists()) directory.mkdirs()
            file.writeText(json)
        } catch (error: Throwable) {
            Slog.w(Slog.PROFILE, "Could not store space identity: ${error.message}")
        }
    }

    /**
     * Builds the set from a hash of the profile id and revision.
     *
     * Deterministic on purpose: the same space always gets the same identifiers, two
     * spaces never collide, and "Modify" is just the next revision.
     */
    private fun derive(profileId: String, virtualUserId: Int, revision: Int): Identity {
        val seed = digest("$profileId#$revision")

        return Identity(
            virtualUserId = virtualUserId,
            revision = revision,
            deviceId = imei(seed),
            androidId = hex(seed, offset = 8, bytes = 8),
            serialNumber = alnum(seed, offset = 16, count = 12),
            wifiMac = mac(seed, offset = 20),
            bluetoothMac = mac(seed, offset = 26),
        )
    }

    private fun digest(input: String): ByteArray =
        MessageDigest.getInstance("SHA-256").digest(input.toByteArray())

    /** 15 digits with a valid Luhn check digit, the shape a real IMEI has. */
    private fun imei(seed: ByteArray): String {
        val body = digits(seed, offset = 0, count = 14)
        var sum = 0
        for ((index, character) in body.withIndex()) {
            var digit = character - '0'
            // Luhn doubles every second digit counting from the right; with a 14-digit
            // body that is the even indices from the left.
            if (index % 2 == 1) {
                digit *= 2
                if (digit > 9) digit -= 9
            }
            sum += digit
        }
        return body + ((10 - sum % 10) % 10)
    }

    private fun digits(seed: ByteArray, offset: Int, count: Int): String =
        buildString(count) {
            for (index in 0 until count) {
                append((seed[(offset + index) % seed.size].toInt() and 0xFF) % 10)
            }
        }

    /**
     * Uppercase letters and digits, which is the shape a device serial actually has.
     *
     * Ambiguous characters are left out of the alphabet: a serial is something people
     * read off a screen and type somewhere else, and O against 0 costs more than the
     * two characters of entropy it buys.
     */
    private fun alnum(seed: ByteArray, offset: Int, count: Int): String =
        buildString(count) {
            for (index in 0 until count) {
                val byte = seed[(offset + index) % seed.size].toInt() and 0xFF
                append(SERIAL_ALPHABET[byte % SERIAL_ALPHABET.length])
            }
        }

    private fun hex(seed: ByteArray, offset: Int, bytes: Int): String =
        buildString(bytes * 2) {
            for (index in 0 until bytes) {
                append("%02x".format(seed[(offset + index) % seed.size].toInt() and 0xFF))
            }
        }

    private fun mac(seed: ByteArray, offset: Int): String =
        (0 until 6).joinToString(":") { index ->
            var octet = seed[(offset + index) % seed.size].toInt() and 0xFF
            if (index == 0) {
                // Clear the multicast bit and set the locally-administered one, so the
                // address is well-formed and cannot be mistaken for a vendor's range.
                octet = (octet and 0xFE) or 0x02
            }
            "%02x".format(octet)
        }

    private companion object {
        const val DIRECTORY = "space_identity"

        /** No I, O, 0, 1: they are indistinguishable in most of the fonts this lands in. */
        const val SERIAL_ALPHABET = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"
    }
}
