import 'package:flutter/foundation.dart';

/// The device identifiers one space presents as its own.
///
/// Generated by Duplika, not read from the device. On API 29+ the host cannot read the
/// IMEI or the serial (`READ_PRIVILEGED_PHONE_STATE` is system-only) and since API 23
/// both MAC addresses come back as `02:00:00:00:00:00`, so "the device's identifiers"
/// is not a thing an app can show. A space's identity being its own is also the point.
///
/// See `SpaceIdentityStore` for how the values are derived, and
/// [isolatedFromGuests] for what is not yet true about them.
@immutable
class SpaceIdentity {
  const SpaceIdentity({
    required this.virtualUserId,
    required this.revision,
    required this.deviceId,
    required this.androidId,
    required this.serialNumber,
    required this.wifiMac,
    required this.bluetoothMac,
  });

  factory SpaceIdentity.fromMap(Map<String, dynamic> map) => SpaceIdentity(
        virtualUserId: map['virtualUserId'] as int? ?? 0,
        revision: map['revision'] as int? ?? 0,
        deviceId: map['deviceId'] as String? ?? '',
        androidId: map['androidId'] as String? ?? '',
        serialNumber: map['serialNumber'] as String? ?? '',
        wifiMac: map['wifiMac'] as String? ?? '',
        bluetoothMac: map['bluetoothMac'] as String? ?? '',
      );

  final int virtualUserId;

  /// How many times this space's identity has been regenerated. 0 is the original set,
  /// which is what Reset returns to.
  final int revision;

  final String deviceId;
  final String androidId;
  final String serialNumber;
  final String wifiMac;
  final String bluetoothMac;

  /// Whether guest apps actually read these values.
  ///
  /// **False today.** Bcore has the hooks (`DeviceIdProxy`,
  /// `ISettingsProviderProxy`) but no API to point them at a per-space store, so a
  /// guest still sees the device's own identifiers. Wiring it up means a class override
  /// through `engine-patches/apply-runtime-overrides.sh`, which is a separate change.
  ///
  /// A constant rather than a runtime check because there is nothing to check yet: the
  /// day the override ships, this becomes a real query and every screen that reads it
  /// starts telling the truth without being rewritten.
  static const bool isolatedFromGuests = false;

  bool get isModified => revision > 0;
}
